name: Test and build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Node.js 16.x testing stuff
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: echo "Before tests"
      - run: ls -la
      - run: npm ci
      - run: npm run test
      - name: Download test coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage_report
          path: coverage_res

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - name: Node.js 16.x setup
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: echo "After tests"
      - run: ls -la
      - run: npm ci
      - run: npm run build
      - name: Download build files
        uses: actions/upload-artifact@v3
        with:
          name: lab_compiled
          path: dist
